language: ruby
rvm:
  - 1.9.3
  - 2.0.0

os:
  - linux
  - osx

matrix:
  include:
    # Linux
    - rvm: 2.1.8
    - rvm: 2.2.4
    # OSX
    - rvm: 2.1.2
      os: osx
    - rvm: 2.1.3
      os: osx


install:
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec rake

notifications:
  email: false
