language: ruby
rvm:
  - 1.9.3

install:
#  - gem build rational2.gemspec
#  - gem install rational2
#  - bundle install --jobs=3 --retry=3 --deployment
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec rake

notifications:
  email: false
