environment:
  matrix:
    - ruby_version: "19"
    - ruby_version: "19-x64"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler
#  - bundle install --jobs=3 --retry=3 --deployment
  - bundle install --jobs=3 --retry=3

test_script:
  - bundle exec rake

build: off
